# Generated by Django 4.2.1 on 2023-05-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akintunde', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/blog'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/gallery'),
        ),
    ]
