# Generated by Django 4.2.1 on 2023-09-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akintunde', '0010_alter_blog_description_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
