# Generated by Django 4.2.1 on 2023-08-19 03:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akintunde', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='biography',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
