# Generated by Django 4.2 on 2023-09-03 22:34

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('akintunde', '0010_alter_blog_description_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='video',
            name='videourl',
            field=embed_video.fields.EmbedVideoField(default='', null=True),
        ),
    ]
