# Generated by Django 4.2.1 on 2023-09-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akintunde', '0011_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='videourl',
        ),
    ]
