# Generated by Django 4.2 on 2023-09-02 23:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akintunde', '0013_alter_video_videourl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/exhibitions')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name=True)),
            ],
        ),
    ]
