# Generated by Django 4.2 on 2023-09-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akintunde', '0014_exhibition'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
