# Generated by Django 4.2 on 2023-09-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akintunde', '0015_exhibition_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='upload_date',
        ),
    ]
